name: Browser tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: Delemangi/.github/.github/workflows/playwright.yaml@main
    with:
      node-version: '24'
      build-command: npm run build
      test-command: npm run test:e2e
      artifact-name: browser-test-failure
